bungee:
  # If this is false, local sqlite database will be used.
  # and all after settings will be ignored.
  enabled: false
  # Haze will wait for data in MAIN THREAD this milli seconds.
  # larger value cause heavy lagg on data getting.
  # If your bungee has slow speed connection, put more large value.
  data-get-timeout: 500