#
#  This file is part of Haze.
#
#  Haze, Player's Point Manager.
#  Copyright (C) 2019 OKOCRAFT
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: LazyGon
commands:
  haze:
    description: Base Command of Haze plugin.

permissions:
# command permissions
  haze.*:
    description: Permission for all command
    children:
      haze.add: true
      haze.remove: true
      haze.increase: true
      haze.decrease: true
      haze.set: true
      haze.reload: true
    default: op
  haze.add:
    description: Permission for command /haze add <point-name>
    default: op
  haze.remove:
    description: Permission for command /haze remove <point-name>
    default: op
  haze.increase:
    description: Permission for command /haze increase <point-name> <player> <amount>
    default: op
  haze.decrease:
    description: Permission for command /haze decrease <point-name> <player> <amount>
    default: op
  haze.set:
    description: Permission for command /haze set <point-name> <player> <amount>
    default: op
  haze.reload:
    description: Permission for command /haze reload
    default: op
  haze.get:
    description: Permission for command /haze get <point-name> <player>
    default: op
  haze.pointlist:
    description: Permission for command /haze pointlist
    default: op